name: CI

on:
  pull_request:

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - name: Run cargo test
        run: nix develop --command cargo test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/determinate-nix-action@v3
      - name: Run E2E checks with nix-fast-build
        run: |
          nix run nixpkgs#nix-fast-build -- \
            --no-nom \
            --skip-cached
